[package]
name = "macbookfan"
version = "0.2.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]

[dependencies]
clap = "2.26"
lazy_static = "0.2"
pid_control = "0.7"
clippy = {version = "*", optional = true}

[features]
default = []
